apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "project.fullname" . }}-send-change-card-number-cron-job
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: registry.pinsvc.net/ops/buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl 'http://{{ template "project.fullname" . }}:{{ .Values.service.clusterZonePort }}/refunds/saman/cancel'
          restartPolicy: OnFailure
