service:
  port: 9000
  clusterZonePort: 9001

resources: {}
ingressClass: local
configResource: app.conf


ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, HEAD"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:9000, http://localhost, http://localhost:4200"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/cors-allow-headers: "access-control-allow-origin, lang, x-auth-id, x-auth-token, Content-Type, x-mock-response-code, authorization"

